name: benchmark_koniq10k/shared_5t_4a_clipfeat_mbv3_koniq_seed1
model_type: MultiDimSharedIQAModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

update_until_better: false

define: &img_size_oneside 384 
define: &img_size [*img_size_oneside, *img_size_oneside]

define: &setting 2
define: &backbone resnet50

define: &train_batch_size 16 
define: &test_batch_size 1 

define: &pretrained_aesthetic_model_path MDIQA/checkpoints/net_best_PARA_val_color.pth

define: &pretrained_technology_model_path [MDIQA/checkpoints/net_freeze_backbone.pth,
                                           MDIQA/checkpoints/net_best_koniq10k_val_head0_head0.pth,
                                           MDIQA/checkpoints/net_best_koniq10k_val_head1_head1.pth,
                                           MDIQA/checkpoints/net_best_koniq10k_val_head2_head2.pth,
                                           MDIQA/checkpoints/net_best_koniq10k_val_head3_head3.pth,
                                           MDIQA/checkpoints/net_best_koniq10k_val_head4_head4.pth]

# dataset and data loader settings
datasets:

  train_1:
    name: koniq10k
    type: KonIQ
    dataroot_target: ./datasets/koniq10k/512x384
    meta_info_file: ./datasets/meta_info/meta_info_KonIQ10kDataset.csv
    split_file: ./datasets/meta_info/koniq10k/koniq10k_seed1.pkl
    mos_range: [0, 100]
    lower_better: false 
    mos_normalize: true

    augment:
      hflip: true
      random_crop: *img_size_oneside
    augment_aes: ~
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: *train_batch_size
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: koniq10k
    type: KonIQ
    dataroot_target: ./datasets/koniq10k/512x384
    meta_info_file: ./datasets/meta_info/meta_info_KonIQ10kDataset.csv
    split_file: ./datasets/meta_info/koniq10k/koniq10k_seed1.pkl


# training settings
train:
  optim:
    type: AdamW
    lr: !!float 1e-5  # 3e-5
    weight_decay: !!float 1e-5
  
  scheduler:
    type: CosineAnnealingLR
    T_max: 50 
    eta_min: 0 

  total_iter: 50000
  total_epoch: ~
  warmup_iter: -1  # no warm up
  
  # losses
  losses:
    loss1:
      datasets:
        d1: koniq10k
      opt:
        type: FidelityLoss
        loss_weight: !!float 0.0

    loss2:
      datasets:
        d1: koniq10k
      opt:
        type: NiNLoss
        loss_weight: !!float 1.0

    loss3:
      datasets:
        d1: koniq10k
      opt:
        type: MSELoss
        loss_weight: !!float 1.0


# validation settings
val:
  val_freq: !!float 500  # 500 / 20
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately 
  metrics:
    srcc: 
      type: calculate_srcc

    plcc: 
      type: calculate_plcc

# logging settings
logger:
  print_freq: 100
  save_latest_freq: !!float 500000
  log_imgs_freq: 1000
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True

network:
  type: MultiDimFusionWeightedMLP
  num_dim: 1
  dataset_specific_weighted: false
  instance_specific_weighted: true
  semantic_model_name: mobilenetv3_large_100.ra_in1k
  local_score: true
  semantic_feat: clip_RN50

path:
  strict_load_g: true
  resume_state: ~
  pretrain_network: ~
  # pretrain_network: checkpoints/mdiqa_shared_5t_4a_mbv3_koniq_seed1.pth
  # pretrain_network: checkpoints/mdiqa_shared_5t_4a_clipfeat_localv4_mbv3_koniq_seed1.pth

networks:
# network structures

  technology:
    network:
      type: CFANet_Shared
      setting: *setting
      num_class: 5
      num_crop: 1 
      crop_size: *img_size
      semantic_model_name: *backbone
      pretrained_model_path: *pretrained_technology_model_path

    scale: 1

  aesthetic:
    network:
      type: CFANet_Shared
      setting: *setting
      num_class: 4
      num_crop: 1 
      crop_size: *img_size
      semantic_model_name: *backbone
      pretrained_model_path: *pretrained_aesthetic_model_path

    scale: 1
